import { StyleSheet } from 'react-native';

const createStyles = (isDark: boolean) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
        },
        header: {
            paddingBottom: 16,
            elevation: 4,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 4,
        },
        headerContent: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 16,
            paddingTop: 12,
            paddingBottom: 16,
        },
        backButton: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerTitleContainer: {
            flex: 1,
            alignItems: 'center',
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: '#FFFFFF',
        },
        headerSubtitle: {
            fontSize: 13,
            color: 'rgba(255, 255, 255, 0.8)',
            marginTop: 2,
        },
        headerSpacer: {
            width: 40,
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            borderRadius: 12,
            paddingHorizontal: 16,
            marginHorizontal: 16,
            marginTop: 8,
        },
        searchInput: {
            flex: 1,
            paddingVertical: 12,
            paddingHorizontal: 12,
            fontSize: 16,
            color: '#FFFFFF',
        },
        exerciseList: {
            flex: 1,
        },
        exerciseListContent: {
            paddingHorizontal: 16,
            paddingTop: 16,
            paddingBottom: 20,
        },
        exerciseLoadingContainer: {
            alignItems: 'center',
            paddingVertical: 60,
        },
        exerciseLoadingText: {
            marginTop: 16,
            fontSize: 16,
            color: isDark ? '#9CA3AF' : '#6B7280',
        },
        exerciseGrid: {
            gap: 20,
            paddingBottom: 20,
        },
        categorySection: {
            marginBottom: 16,
        },
        categoryHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#1e293b' : '#F3E8FF',
            paddingVertical: 16,
            paddingHorizontal: 16,
            borderRadius: 16,
            marginBottom: 2,
            gap: 12,
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#E9D5FF',
            shadowColor: isDark ? '#9333ea' : '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: isDark ? 0.3 : 0.1,
            shadowRadius: 4,
            elevation: 3,
        },
        categoryIconCircle: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: isDark ? '#7e22ce' : '#FFFFFF',
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderColor: isDark ? '#9333ea' : '#E9D5FF',
        },
        categoryTitle: {
            fontSize: 17,
            fontWeight: '700',
            color: isDark ? '#f1f5f9' : '#7E22CE',
            flex: 1,
            letterSpacing: 0.3,
        },
        categoryBadge: {
            backgroundColor: isDark ? '#7e22ce' : '#9333EA',
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 14,
            minWidth: 32,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: isDark ? '#9333ea' : '#7e22ce',
        },
        categoryBadgeText: {
            fontSize: 13,
            fontWeight: 'bold',
            color: '#FFFFFF',
        },
        categoryExercises: {
            gap: 10,
            paddingTop: 12,
            paddingHorizontal: 4,
        },
        exerciseCard: {
            backgroundColor: isDark ? '#1e293b' : '#F9FAFB',
            borderRadius: 14,
            padding: 16,
            borderWidth: 1,
            borderColor: isDark ? '#475569' : '#E5E7EB',
            borderLeftWidth: 3,
            borderLeftColor: isDark ? '#a855f7' : '#9333EA',
            shadowColor: isDark ? '#000' : '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.3 : 0.05,
            shadowRadius: 2,
            elevation: 2,
        },
        exerciseCardHeader: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        exerciseIconCircle: {
            width: 48,
            height: 48,
            borderRadius: 24,
            backgroundColor: isDark ? '#475569' : '#F3E8FF',
            alignItems: 'center',
            justifyContent: 'center',
            marginRight: 14,
            overflow: 'hidden',
            borderWidth: 2,
            borderColor: isDark ? '#64748b' : '#E9D5FF',
        },
        exerciseImage: {
            width: 48,
            height: 48,
            borderRadius: 24,
        },
        exerciseInfo: {
            flex: 1,
        },
        exerciseName: {
            fontSize: 16,
            fontWeight: '600',
            color: isDark ? '#f8fafc' : '#111827',
            letterSpacing: 0.2,
        },
        exerciseDescription: {
            fontSize: 14,
            color: isDark ? '#D1D5DB' : '#6B7280',
            lineHeight: 20,
        },
        exerciseEmptyState: {
            alignItems: 'center',
            paddingVertical: 60,
        },
        exerciseEmptyText: {
            fontSize: 16,
            color: isDark ? '#9CA3AF' : '#6B7280',
            marginTop: 16,
            textAlign: 'center',
        },
    });

export default createStyles;
