import { StyleSheet } from 'react-native';

const createStyles = (isDark: boolean) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
        },
        header: {
            paddingBottom: 14,
            elevation: 2,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 3,
        },
        headerContent: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 16,
            paddingTop: 10,
            paddingBottom: 14,
        },
        backButton: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerTitleContainer: {
            flex: 1,
            alignItems: 'center',
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: '#FFFFFF',
        },
        headerSubtitle: {
            fontSize: 13,
            color: 'rgba(255, 255, 255, 0.8)',
            marginTop: 2,
        },
        headerSpacer: {
            width: 40,
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: 'rgba(255, 255, 255, 0.25)',
            borderRadius: 12,
            paddingHorizontal: 14,
            marginHorizontal: 16,
            marginTop: 4,
        },
        searchInput: {
            flex: 1,
            paddingVertical: 10,
            paddingHorizontal: 10,
            fontSize: 15,
            color: '#FFFFFF',
        },
        exerciseList: {
            flex: 1,
        },
        exerciseListContent: {
            paddingHorizontal: 16,
            paddingTop: 12,
            paddingBottom: 16,
        },
        exerciseLoadingContainer: {
            alignItems: 'center',
            paddingVertical: 60,
        },
        exerciseLoadingText: {
            marginTop: 16,
            fontSize: 16,
            color: isDark ? '#9CA3AF' : '#6B7280',
        },
        exerciseGrid: {
            gap: 10,
            paddingBottom: 12,
        },
        categorySection: {
            marginBottom: 10,
        },
        categoryHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: isDark ? '#1e293b' : '#FFFFFF',
            paddingVertical: 12,
            paddingHorizontal: 14,
            borderRadius: 12,
            marginBottom: 6,
            gap: 10,
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#E5E7EB',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.2 : 0.04,
            shadowRadius: 2,
            elevation: 1,
        },
        categoryIconCircle: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: isDark ? '#7e22ce' : '#F3E8FF',
            alignItems: 'center',
            justifyContent: 'center',
        },
        categoryTitle: {
            fontSize: 15,
            fontWeight: '600',
            color: isDark ? '#f1f5f9' : '#111827',
            flex: 1,
        },
        categoryBadge: {
            backgroundColor: isDark ? '#334155' : '#F3F4F6',
            paddingHorizontal: 10,
            paddingVertical: 4,
            borderRadius: 10,
            minWidth: 28,
            alignItems: 'center',
        },
        categoryBadgeText: {
            fontSize: 12,
            fontWeight: '600',
            color: isDark ? '#cbd5e1' : '#6B7280',
        },
        categoryExercises: {
            gap: 6,
            paddingTop: 6,
            paddingHorizontal: 0,
        },
        exerciseCard: {
            backgroundColor: isDark ? '#1e293b' : '#FFFFFF',
            borderRadius: 10,
            padding: 12,
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#E5E7EB',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: isDark ? 0.15 : 0.03,
            shadowRadius: 1,
            elevation: 1,
        },
        exerciseCardHeader: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        exerciseIconCircle: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: isDark ? '#334155' : '#F9FAFB',
            alignItems: 'center',
            justifyContent: 'center',
            marginRight: 12,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: isDark ? '#475569' : '#E5E7EB',
        },
        exerciseImage: {
            width: 40,
            height: 40,
            borderRadius: 20,
        },
        exerciseInfo: {
            flex: 1,
        },
        exerciseName: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#f8fafc' : '#111827',
        },
        exerciseDescription: {
            fontSize: 14,
            color: isDark ? '#D1D5DB' : '#6B7280',
            lineHeight: 20,
        },
        exerciseEmptyState: {
            alignItems: 'center',
            paddingVertical: 60,
        },
        exerciseEmptyText: {
            fontSize: 16,
            color: isDark ? '#9CA3AF' : '#6B7280',
            marginTop: 16,
            textAlign: 'center',
        },
    });

export default createStyles;
