import { StyleSheet } from 'react-native';

const createStyles = (isDark: boolean) =>
    StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
        },
        loadingContainer: {
            justifyContent: 'center',
            alignItems: 'center',
        },
        timerHeader: {
            paddingHorizontal: 16,
            paddingBottom: 20,
        },
        timerContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 16,
        },
        timerLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        timerIconContainer: {
            width: 48,
            height: 48,
            borderRadius: 24,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        timerLabel: {
            fontSize: 12,
            color: 'rgba(255, 255, 255, 0.8)',
            marginBottom: 2,
        },
        timerValue: {
            fontSize: 28,
            fontWeight: 'bold',
            color: '#fff',
            fontFamily: 'monospace',
        },
        pauseButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            paddingHorizontal: 16,
            paddingVertical: 10,
            borderRadius: 20,
        },
        pauseButtonText: {
            color: '#fff',
            fontSize: 14,
            fontWeight: '600',
        },
        headerActions: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        backButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
            paddingHorizontal: 12,
            paddingVertical: 8,
            borderRadius: 16,
        },
        backButtonText: {
            color: '#fff',
            fontSize: 14,
            fontWeight: '600',
        },
        headerRight: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        cancelButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            backgroundColor: '#fff',
            paddingHorizontal: 12,
            paddingVertical: 8,
            borderRadius: 16,
        },
        cancelButtonText: {
            color: '#ef4444',
            fontSize: 14,
            fontWeight: '600',
        },
        finishButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            backgroundColor: '#10b981',
            paddingHorizontal: 12,
            paddingVertical: 8,
            borderRadius: 16,
        },
        finishButtonDisabled: {
            opacity: 0.6,
        },
        finishButtonText: {
            color: '#fff',
            fontSize: 14,
            fontWeight: '600',
        },
        titleContainer: {
            marginBottom: 20,
            paddingHorizontal: 20,
        },
        title: {
            fontSize: 28,
            fontWeight: '700',
            color: isDark ? '#fff' : '#1f2937', // Changed from light gray to dark gray
            marginBottom: 4,
        },
        subtitle: {
            fontSize: 14,
            color: isDark ? '#94a3b8' : '#6b7280', // Changed for better contrast
            fontWeight: '500',
        },

        content: {
            flex: 1,
        },
        contentContainer: {
            padding: 16,
            gap: 16,
        },
        addExerciseButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: isDark ? '#1e293b' : '#fff',
            paddingVertical: 16,
            borderRadius: 12,
            borderWidth: 2,
            borderColor: isDark ? '#334155' : '#e5e7eb',
            borderStyle: 'dashed',
        },
        addExerciseButtonText: {
            fontSize: 16,
            fontWeight: '600',
            color: '#3b82f6',
        },
        exerciseCard: {
            backgroundColor: isDark ? '#1e293b' : '#fff',
            borderRadius: 12,
            padding: 16,
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#e5e7eb',
        },
        exerciseHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 16,
        },
        exerciseHeaderLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            flex: 1,
        },
        exerciseNumber: {
            width: 32,
            height: 32,
            borderRadius: 16,
            backgroundColor: '#3b82f6',
            alignItems: 'center',
            justifyContent: 'center',
        },
        exerciseNumberText: {
            fontSize: 14,
            fontWeight: 'bold',
            color: '#fff',
        },
        exerciseImage: {
            width: 48,
            height: 48,
            borderRadius: 8,
        },
        exerciseInfo: {
            flex: 1,
        },
        exerciseName: {
            fontSize: 16,
            fontWeight: '600',
            color: isDark ? '#e2e8f0' : '#111827',
            marginBottom: 2,
        },
        exerciseCategory: {
            fontSize: 12,
            color: isDark ? '#94a3b8' : '#6b7280',
        },
        setsContainer: {
            gap: 8,
            marginBottom: 12,
        },
        setRow: {
            position: 'relative',
            overflow: 'hidden',
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
            borderRadius: 10,
            borderWidth: 2,
            borderColor: isDark ? '#334155' : '#e5e7eb',
        },
        setRowCompleted: {
            backgroundColor: isDark ? '#064e3b' : '#d1fae5',
            borderColor: '#10b981',
        },
        setRowResting: {
            borderColor: '#3b82f6',
            backgroundColor: isDark ? '#0f172a' : '#eff6ff',
        },
        restProgressBar: {
            position: 'absolute',
            top: 0,
            left: 0,
            bottom: 0,
            backgroundColor: isDark ? '#3b82f6' : '#3b82f6',
            opacity: isDark ? 0.4 : 0.3,
        },
        setRowContent: {
            position: 'relative',
            zIndex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            padding: 12,
            gap: 10,
        },
        checkButton: {
            width: 28,
            height: 28,
            borderRadius: 14,
            borderWidth: 2,
            borderColor: isDark ? '#64748b' : '#d1d5db',
            backgroundColor: isDark ? '#1e293b' : '#fff',
            alignItems: 'center',
            justifyContent: 'center',
        },
        checkButtonCompleted: {
            backgroundColor: '#10b981',
            borderColor: '#10b981',
        },
        setInfo: {
            minWidth: 50,
        },
        setLabel: {
            fontSize: 13,
            fontWeight: '600',
            color: isDark ? '#e2e8f0' : '#111827',
            marginBottom: 2,
        },
        completedLabel: {
            fontSize: 10,
            color: '#10b981',
        },
        setInputs: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            flex: 1,
        },
        inputGroup: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
            flex: 1,
        },
        input: {
            flex: 1,
            height: 32,
            backgroundColor: isDark ? '#0f172a' : '#fff',
            borderWidth: 1,
            borderColor: isDark ? '#475569' : '#d1d5db',
            borderRadius: 6,
            paddingHorizontal: 8,
            fontSize: 13,
            color: isDark ? '#e2e8f0' : '#111827',
            textAlign: 'center',
        },
        inputLabel: {
            fontSize: 11,
            color: isDark ? '#94a3b8' : '#6b7280',
        },
        inputSeparator: {
            fontSize: 12,
            color: isDark ? '#64748b' : '#d1d5db',
        },
        setActions: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
        },
        restTimer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        restTimerText: {
            fontSize: 12,
            fontWeight: '600',
            color: '#3b82f6',
            fontFamily: 'monospace',
        },
        addSetButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 6,
            paddingVertical: 10,
            borderRadius: 8,
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#e5e7eb',
            borderStyle: 'dashed',
        },
        addSetButtonText: {
            fontSize: 14,
            fontWeight: '600',
            color: '#3b82f6',
        },
        emptyState: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 60,
        },
        emptyStateTitle: {
            fontSize: 18,
            fontWeight: '600',
            color: isDark ? '#e2e8f0' : '#111827',
            marginTop: 16,
            marginBottom: 8,
        },
        emptyStateText: {
            fontSize: 14,
            color: isDark ? '#94a3b8' : '#6b7280',
            textAlign: 'center',
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'flex-end',
        },
        modalContent: {
            backgroundColor: isDark ? '#1e293b' : '#fff',
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            maxHeight: '80%',
            paddingTop: 20,
        },
        modalHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            marginBottom: 16,
        },
        modalTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: isDark ? '#e2e8f0' : '#111827',
        },
        searchContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
            borderWidth: 1,
            borderColor: isDark ? '#334155' : '#e5e7eb',
            borderRadius: 12,
            paddingHorizontal: 12,
            paddingVertical: 10,
            marginHorizontal: 20,
            marginBottom: 16,
        },
        searchInput: {
            flex: 1,
            fontSize: 15,
            color: isDark ? '#e2e8f0' : '#111827',
        },
        exerciseList: {
            flex: 1,
            paddingHorizontal: 20,
        },
        exerciseListItem: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            backgroundColor: isDark ? '#0f172a' : '#f9fafb',
            padding: 12,
            borderRadius: 10,
            marginBottom: 8,
        },
        exerciseListImage: {
            width: 40,
            height: 40,
            borderRadius: 8,
        },
        exerciseListInfo: {
            flex: 1,
        },
        exerciseListName: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#e2e8f0' : '#111827',
            marginBottom: 2,
        },
        exerciseListCategory: {
            fontSize: 12,
            color: isDark ? '#94a3b8' : '#6b7280',
        },
        loadingState: {
            alignItems: 'center',
            paddingVertical: 40,
            gap: 12,
        },
        loadingText: {
            fontSize: 14,
            color: isDark ? '#94a3b8' : '#6b7280',
        },
        emptySearchState: {
            alignItems: 'center',
            paddingVertical: 40,
        },
        emptySearchText: {
            fontSize: 14,
            color: isDark ? '#94a3b8' : '#6b7280',
            marginTop: 12,
        },
    });

export default createStyles;