import { StyleSheet } from 'react-native';

const createStyles = (isDark: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: isDark ? '#0f172a' : '#f9fafb',
    },
    scrollView: {
        flex: 1,
    },
    contentWrapper: {
        padding: 16,
        paddingBottom: 32,
    },
    section: {
        marginBottom: 24,
    },
    sectionHeader: {
        marginBottom: 16,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    iconBadge: {
        width: 48,
        height: 48,
        borderRadius: 14,
        overflow: 'hidden',
    },
    iconBadgeGradient: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: isDark ? '#f1f5f9' : '#111827',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 13,
        color: isDark ? '#94a3b8' : '#6b7280',
        fontWeight: '500',
    },
    actionButtonsContainer: {
        gap: 10,
        marginBottom: 20,
    },
    actionButtonsRow: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 10,
    },
    actionCard: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: isDark ? '#1e293b' : '#fff',
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: isDark ? '#334155' : '#e5e7eb',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDark ? 0.3 : 0.05,
        shadowRadius: 4,
        gap: 10,
    },
    actionCardFull: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: isDark ? '#1e293b' : '#fff',
        borderRadius: 16,
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: isDark ? '#334155' : '#e5e7eb',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: isDark ? 0.3 : 0.05,
        shadowRadius: 4,
        gap: 10,
    },
    actionIconCircle: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 3,
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    actionCardTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: isDark ? '#f1f5f9' : '#111827',
    },
    loadingContainer: {
        marginTop: 8,
    },
    loadingCard: {
        borderRadius: 16,
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 15,
        color: isDark ? '#a78bfa' : '#7e22ce',
        fontWeight: '600',
    },
    emptyState: {
        marginTop: 8,
    },
    emptyStateGradient: {
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
    },
    emptyIconContainer: {
        width: 96,
        height: 96,
        borderRadius: 24,
        overflow: 'hidden',
        marginBottom: 24,
        elevation: 4,
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    emptyIconGradient: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyStateTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: isDark ? '#f1f5f9' : '#111827',
        marginBottom: 12,
    },
    emptyStateText: {
        fontSize: 15,
        color: isDark ? '#94a3b8' : '#6b7280',
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 24,
        paddingHorizontal: 8,
    },
    emptyStateFeatures: {
        width: '100%',
        marginBottom: 28,
        gap: 12,
    },
    featureItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: isDark ? '#1e293b' : '#fff',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        gap: 12,
    },
    featureIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: isDark ? '#7e22ce' : '#f3e8ff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    featureText: {
        fontSize: 15,
        fontWeight: '600',
        color: isDark ? '#cbd5e1' : '#374151',
    },
    emptyStateButtons: {
        width: '100%',
        gap: 12,
    },
    emptyPrimaryButton: {
        borderRadius: 14,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: '#9333ea',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    emptyPrimaryGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        gap: 10,
    },
    emptyPrimaryText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
    emptySecondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: isDark ? '#7e22ce' : '#e9d5ff',
        backgroundColor: isDark ? '#1e293b' : '#fff',
        gap: 8,
    },
    emptySecondaryText: {
        fontSize: 15,
        fontWeight: '700',
        color: isDark ? '#a78bfa' : '#7e22ce',
    },
    list: {
        gap: 12,
    },
    unsortedSection: {
        marginTop: 12,
    },
    unsortedHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: isDark ? '#1e293b' : '#f3f4f6',
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 12,
        marginBottom: 12,
        gap: 8,
    },
    unsortedTemplates: {
        gap: 12,
    },
    unsortedTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: isDark ? '#94a3b8' : '#6b7280',
        flex: 1,
    },
    unsortedBadge: {
        backgroundColor: isDark ? '#334155' : '#fff',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    unsortedBadgeText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: isDark ? '#cbd5e1' : '#6b7280',
    },
});

export default createStyles;
