apiVersion: v1
kind: Service
metadata:
  name: fit-verse-api
  labels:
    app: fit-verse-api
spec:
  ports:
  - port: 5004
    targetPort: 5004
    nodePort: 30004
  selector:
    app: fit-verse-api

  type: NodePort