apiVersion: v1
kind: Service
metadata:
  name: mern-fit-verse-backend
  labels:
    app: mern-fit-verse-backend
spec:
  type: ClusterIP
  ports:
    - port: 5004
      targetPort: 5004
  selector:
    app: mern-fit-verse-backend
