apiVersion: v1
kind: Service
metadata:
  name: mern-fit-verse-frontend
  labels:
    app: mern-fit-verse-frontend
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: 5005
  selector:
    app: mern-fit-verse-frontend
