apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitverse-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  # Frontend - fitverse.codewithxjohn.com
  - host: fitverse.codewithxjohn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitverse-frontend
            port:
              number: 80
  # Frontend - www.fitverse.codewithxjohn.com
  - host: www.fitverse.codewithxjohn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitverse-frontend
            port:
              number: 80
  # Backend API - api.fitverse.codewithxjohn.com
  - host: api.fitverse.codewithxjohn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitverse-backend
            port:
              number: 4001
  # Backend API - www.api.fitverse.codewithxjohn.com
  - host: www.api.fitverse.codewithxjohn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fitverse-backend
            port:
              number: 4001
  tls:
  - hosts:
    - fitverse.codewithxjohn.com
    - www.fitverse.codewithxjohn.com
    - api.fitverse.codewithxjohn.com
    - www.api.fitverse.codewithxjohn.com
    secretName: fitverse-tls
