apiVersion: apps/v1
kind: Deployment
metadata:
    name: fit-verse-frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: fit-verse-frontend
    template:
        metadata:
            labels:
                app: fit-verse-frontend
        spec:
            containers:
                - name: fit-verse-frontend
                  image: xjohnfit/fitverse-frontend:1.0.0-18
                  resources:
                      limits:
                          cpu: '1'
                          memory: '512Mi'
                      requests:
                          cpu: '200m'
                          memory: '256Mi'
                  ports:
                      - containerPort: 5005
                  envFrom:
                      - secretRef:
                            name: fit-verse-frontend-secrets
            imagePullSecrets:
                - name: regcred
