import { StyleSheet } from 'react-native';

const HelpAndSupportModalStyles = (isDark: boolean) =>
    StyleSheet.create({
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'flex-end',
        },
        backdropTouchable: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
        },
        modalContainer: {
            backgroundColor: isDark ? '#1f2937' : '#ffffff',
            borderTopLeftRadius: 24,
            borderTopRightRadius: 24,
            maxHeight: '90%',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: -4 },
            shadowOpacity: 0.25,
            shadowRadius: 12,
            elevation: 10,
        },
        handleBar: {
            width: 40,
            height: 5,
            backgroundColor: isDark ? '#4b5563' : '#d1d5db',
            borderRadius: 9999,
            alignSelf: 'center',
            marginTop: 12,
            marginBottom: 8,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingTop: 16,
            paddingBottom: 20,
            borderBottomWidth: 1,
            borderBottomColor: isDark ? '#374151' : '#e5e7eb',
        },
        headerLeft: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
        },
        headerIconContainer: {
            width: 40,
            height: 40,
            borderRadius: 9999,
            backgroundColor: isDark ? 'rgba(59, 130, 246, 0.2)' : '#dbeafe',
            alignItems: 'center',
            justifyContent: 'center',
            marginRight: 12,
        },
        headerTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: isDark ? '#ffffff' : '#111827',
        },
        headerSubtitle: {
            fontSize: 13,
            color: isDark ? '#9ca3af' : '#6b7280',
            marginTop: 2,
        },
        closeButton: {
            width: 32,
            height: 32,
            borderRadius: 9999,
            backgroundColor: isDark ? '#374151' : '#f3f4f6',
            alignItems: 'center',
            justifyContent: 'center',
        },
        scrollView: {
            maxHeight: '100%',
        },
        scrollViewContent: {
            padding: 20,
        },
        infoCard: {
            backgroundColor: isDark ? 'rgba(59, 130, 246, 0.1)' : '#eff6ff',
            padding: 16,
            borderRadius: 12,
            marginBottom: 24,
            flexDirection: 'row',
            alignItems: 'flex-start',
        },
        infoIcon: {
            marginRight: 12,
            marginTop: 2,
        },
        infoTextContainer: {
            flex: 1,
        },
        infoRow: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 12,
        },
        infoRowLast: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        infoLabel: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#93c5fd' : '#3b82f6',
            marginLeft: 12,
            flex: 1,
        },
        infoText: {
            fontSize: 14,
            color: isDark ? '#dbeafe' : '#1e40af',
        },
        fieldContainer: {
            marginBottom: 20,
        },
        fieldLabel: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#ffffff' : '#111827',
            marginBottom: 8,
        },
        disabledField: {
            backgroundColor: isDark ? '#374151' : '#f3f4f6',
            borderRadius: 12,
            padding: 14,
            borderWidth: 1,
            borderColor: isDark ? '#4b5563' : '#e5e7eb',
        },
        disabledFieldText: {
            fontSize: 15,
            color: isDark ? '#9ca3af' : '#6b7280',
        },
        inputLabel: {
            fontSize: 16,
            fontWeight: '600',
            color: isDark ? '#ffffff' : '#111827',
            marginBottom: 12,
        },
        messageContainer: {
            marginBottom: 8,
        },
        textInput: {
            backgroundColor: isDark ? '#374151' : '#f9fafb',
            borderRadius: 12,
            padding: 16,
            fontSize: 16,
            color: isDark ? '#ffffff' : '#111827',
            minHeight: 120,
            textAlignVertical: 'top',
            borderWidth: 1,
            borderColor: isDark ? '#4b5563' : '#e5e7eb',
        },
        characterCount: {
            textAlign: 'right',
            fontSize: 12,
            color: isDark ? '#9ca3af' : '#6b7280',
            marginTop: 8,
        },
        charCount: {
            textAlign: 'right',
            fontSize: 12,
            color: isDark ? '#9ca3af' : '#6b7280',
            marginTop: 8,
        },
        buttonContainer: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 24,
        },
        cancelButton: {
            flex: 1,
            paddingVertical: 16,
            borderRadius: 12,
            backgroundColor: isDark ? '#374151' : '#f3f4f6',
            alignItems: 'center',
            justifyContent: 'center',
        },
        cancelButtonText: {
            fontSize: 16,
            fontWeight: '600',
            color: isDark ? '#d1d5db' : '#374151',
        },
        sendButton: {
            flex: 1,
            paddingVertical: 16,
            borderRadius: 12,
            backgroundColor: '#3b82f6',
            alignItems: 'center',
            justifyContent: 'center',
            flexDirection: 'row',
        },
        sendButtonDisabled: {
            flex: 1,
            paddingVertical: 16,
            borderRadius: 12,
            backgroundColor: isDark ? '#4b5563' : '#d1d5db',
            alignItems: 'center',
            justifyContent: 'center',
            flexDirection: 'row',
        },
        sendButtonText: {
            fontSize: 16,
            fontWeight: 'bold',
            color: '#ffffff',
            marginLeft: 8,
        },
        sendButtonTextDisabled: {
            fontSize: 16,
            fontWeight: 'bold',
            color: isDark ? '#6b7280' : '#9ca3af',
            marginLeft: 8,
        },
    });

export default HelpAndSupportModalStyles;
