import { StyleSheet } from 'react-native';

const SettingsProfileTabStyles = (isDark: boolean) =>
    StyleSheet.create({
        container: {
            paddingBottom: 24,
        },
        photoSection: {
            alignItems: 'center',
            marginBottom: 32,
            marginTop: 8,
        },
        photoContainer: {
            position: 'relative',
        },
        profileImage: {
            width: 144,
            height: 144,
            borderRadius: 9999,
            borderWidth: 4,
            borderColor: isDark ? '#374151' : '#ffffff',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 8,
        },
        profilePlaceholder: {
            width: 144,
            height: 144,
            borderRadius: 9999,
            backgroundColor: isDark ? 'rgba(59, 130, 246, 0.2)' : '#dbeafe',
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 4,
            borderColor: isDark ? '#374151' : '#ffffff',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 8,
        },
        uploadingOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            width: 144,
            height: 144,
            borderRadius: 9999,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            alignItems: 'center',
            justifyContent: 'center',
        },
        cameraButton: {
            position: 'absolute',
            bottom: 0,
            right: 0,
            width: 48,
            height: 48,
            borderRadius: 9999,
            backgroundColor: '#3b82f6',
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 4,
            borderColor: isDark ? '#111827' : '#ffffff',
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 8,
            elevation: 8,
        },
        profileName: {
            fontSize: 20,
            fontWeight: 'bold',
            color: isDark ? '#ffffff' : '#111827',
            marginTop: 20,
        },
        profileUsername: {
            fontSize: 16,
            color: isDark ? '#9ca3af' : '#6b7280',
            marginTop: 4,
        },
        sectionContainer: {
            marginBottom: 32,
        },
        sectionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 20,
        },
        sectionIndicatorBlue: {
            width: 4,
            height: 24,
            backgroundColor: '#3b82f6',
            borderRadius: 9999,
            marginRight: 12,
        },
        sectionIndicatorPurple: {
            width: 4,
            height: 24,
            backgroundColor: '#a855f7',
            borderRadius: 9999,
            marginRight: 12,
        },
        sectionTitle: {
            fontSize: 20,
            fontWeight: 'bold',
            color: isDark ? '#ffffff' : '#111827',
        },
        imageContainer: {
            position: 'relative',
        },
        inputContainer: {
            marginBottom: 20,
        },
        inputLabel: {
            fontSize: 14,
            fontWeight: '600',
            color: isDark ? '#d1d5db' : '#374151',
            marginBottom: 10,
        },
        textInput: {
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: isDark ? '#1f2937' : '#ffffff',
            borderRadius: 16,
            fontSize: 16,
            color: isDark ? '#ffffff' : '#111827',
            borderWidth: 2,
            borderColor: isDark ? '#374151' : '#e5e7eb',
        },
        dateButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 16,
            backgroundColor: isDark ? '#1f2937' : '#ffffff',
            borderRadius: 16,
            borderWidth: 2,
            borderColor: isDark ? '#374151' : '#e5e7eb',
        },
        dateButtonText: {
            flex: 1,
            fontSize: 16,
            color: isDark ? '#ffffff' : '#111827',
        },
        dateButtonPlaceholder: {
            flex: 1,
            fontSize: 16,
            color: isDark ? '#6b7280' : '#9ca3af',
        },
        rowContainer: {
            flexDirection: 'row',
            gap: 16,
            marginBottom: 20,
        },
        halfInputContainer: {
            flex: 1,
        },
        genderButtonsContainer: {
            flexDirection: 'row',
            gap: 12,
        },
        genderButton: {
            flex: 1,
            paddingHorizontal: 16,
            paddingVertical: 16,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: isDark ? '#374151' : '#e5e7eb',
            backgroundColor: isDark ? '#1f2937' : '#ffffff',
        },
        genderButtonActive: {
            flex: 1,
            paddingHorizontal: 16,
            paddingVertical: 16,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: '#3b82f6',
            backgroundColor: '#3b82f6',
        },
        genderButtonText: {
            textAlign: 'center',
            fontWeight: '600',
            fontSize: 16,
            textTransform: 'capitalize',
            color: isDark ? '#ffffff' : '#111827',
        },
        genderButtonTextActive: {
            textAlign: 'center',
            fontWeight: '600',
            fontSize: 16,
            textTransform: 'capitalize',
            color: '#ffffff',
        },
        goalButton: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 16,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: isDark ? '#374151' : '#e5e7eb',
            backgroundColor: isDark ? '#1f2937' : '#ffffff',
            marginBottom: 12,
        },
        goalButtonActive: {
            flexDirection: 'row',
            alignItems: 'center',
            paddingHorizontal: 20,
            paddingVertical: 16,
            borderRadius: 16,
            borderWidth: 2,
            borderColor: '#3b82f6',
            backgroundColor: '#3b82f6',
            marginBottom: 12,
        },
        goalButtonSpacing: {
            marginTop: 12,
        },
        goalIconContainer: {
            width: 40,
            height: 40,
            borderRadius: 9999,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: isDark ? '#374151' : '#e5e7eb',
        },
        goalIconContainerActive: {
            width: 40,
            height: 40,
            borderRadius: 9999,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'rgba(255, 255, 255, 0.2)',
        },
        goalButtonText: {
            marginLeft: 16,
            fontWeight: '600',
            fontSize: 16,
            flex: 1,
            color: isDark ? '#ffffff' : '#111827',
        },
        goalButtonTextActive: {
            marginLeft: 16,
            fontWeight: '600',
            fontSize: 16,
            flex: 1,
            color: '#ffffff',
        },
        updateButton: {
            marginBottom: 24,
        },
        updateButtonGradient: {
            paddingVertical: 18,
            borderRadius: 16,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
        },
        updateButtonText: {
            color: '#ffffff',
            fontWeight: 'bold',
            fontSize: 18,
            marginLeft: 12,
        },
        logoutButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#dc2626',
            paddingHorizontal: 24,
            paddingVertical: 16,
            borderRadius: 12,
        },
        logoutButtonText: {
            color: '#ffffff',
            fontWeight: 'bold',
            fontSize: 16,
            marginLeft: 8,
        },
    });

export default SettingsProfileTabStyles;
