import { StyleSheet } from 'react-native';

const NotificationBellStyles = StyleSheet.create({
    bellButton: {
        position: 'relative',
        padding: 8,
        borderRadius: 9999,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: '#EF4444',
        borderRadius: 9999,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 4,
    },
    badgeText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    modalContainerDark: {
        flex: 1,
        backgroundColor: '#111827',
    },
    modalHeader: {
        backgroundColor: '#3B82F6',
        paddingTop: 48,
        paddingBottom: 16,
        paddingHorizontal: 16,
    },
    modalHeaderDark: {
        backgroundColor: '#2563EB',
        paddingTop: 48,
        paddingBottom: 16,
        paddingHorizontal: 16,
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 40,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    headerBadge: {
        backgroundColor: '#EF4444',
        borderRadius: 9999,
        marginLeft: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    headerBadgeText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: 'bold',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    deleteButton: {
        marginRight: 12,
        padding: 8,
    },
    closeButton: {
        padding: 8,
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 48,
    },
    loadingText: {
        color: '#4B5563',
        marginTop: 16,
    },
    loadingTextDark: {
        color: '#9CA3AF',
        marginTop: 16,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 48,
    },
    emptyTitle: {
        color: '#4B5563',
        fontWeight: '500',
        marginTop: 16,
    },
    emptyTitleDark: {
        color: '#9CA3AF',
        fontWeight: '500',
        marginTop: 16,
    },
    emptySubtitle: {
        color: '#6B7280',
        fontSize: 14,
        marginTop: 8,
    },
    emptySubtitleDark: {
        color: '#6B7280',
        fontSize: 14,
        marginTop: 8,
    },
    notificationItem: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    notificationItemUnread: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#EFF6FF',
    },
    notificationItemDark: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#1F2937',
        backgroundColor: '#1F2937',
    },
    notificationItemUnreadDark: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#1F2937',
        backgroundColor: 'rgba(59, 130, 246, 0.2)',
    },
    notificationContent: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    avatarContainer: {
        width: 48,
        height: 48,
        borderRadius: 9999,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#E5E7EB',
    },
    avatarContainerDark: {
        width: 48,
        height: 48,
        borderRadius: 9999,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#374151',
    },
    avatar: {
        width: '100%',
        height: '100%',
    },
    avatarPlaceholder: {
        width: 48,
        height: 48,
        borderRadius: 9999,
        backgroundColor: '#D1D5DB',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#E5E7EB',
    },
    avatarPlaceholderDark: {
        width: 48,
        height: 48,
        borderRadius: 9999,
        backgroundColor: '#374151',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#374151',
    },
    notificationTextContainer: {
        flex: 1,
        marginLeft: 12,
    },
    notificationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    notificationHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    notificationMessage: {
        color: '#111827',
        fontWeight: '500',
        fontSize: 14,
        marginLeft: 8,
        flex: 1,
    },
    notificationMessageDark: {
        color: '#F3F4F6',
        fontWeight: '500',
        fontSize: 14,
        marginLeft: 8,
        flex: 1,
    },
    unreadDot: {
        width: 8,
        height: 8,
        backgroundColor: '#3B82F6',
        borderRadius: 9999,
        marginLeft: 8,
    },
    timestamp: {
        color: '#6B7280',
        fontSize: 12,
        marginTop: 4,
    },
    timestampDark: {
        color: '#9CA3AF',
        fontSize: 12,
        marginTop: 4,
    },
});

export default NotificationBellStyles;
