import { StyleSheet } from 'react-native';

const ProfileHeaderStyles = StyleSheet.create({
    container: {
        backgroundColor: '#FFFFFF',
    },
    containerDark: {
        backgroundColor: '#111827',
    },
    nameContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    topRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 4,
        width: '100%',
        paddingHorizontal: 8,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 9999,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    spacer: {
        width: 40,
    },
    nameWrapper: {
        flex: 1,
        marginHorizontal: 8,
    },
    name: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    moreButton: {
        width: 40,
        height: 40,
        borderRadius: 9999,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    username: {
        color: '#FFFFFF',
        fontSize: 14,
        opacity: 0.9,
    },
    chipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginBottom: 16,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 9999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        marginRight: 8,
        marginBottom: 8,
    },
    chipLast: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 9999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        marginBottom: 8,
    },
    chipText: {
        marginLeft: 6,
        fontSize: 12,
        fontWeight: '500',
        color: '#FFFFFF',
    },
    chipTextCapitalize: {
        marginLeft: 6,
        fontSize: 12,
        fontWeight: '500',
        color: '#FFFFFF',
        textTransform: 'capitalize',
    },
    goalChip: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 9999,
        paddingHorizontal: 16,
        paddingVertical: 10,
        marginBottom: 16,
        alignSelf: 'center',
    },
    goalContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    goalLabel: {
        marginLeft: 8,
        fontSize: 12,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    goalValue: {
        marginLeft: 6,
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.95)',
    },
    statsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    statButton: {
        flex: 1,
        alignItems: 'center',
        borderRightWidth: 1,
        borderRightColor: 'rgba(255, 255, 255, 0.3)',
        paddingRight: 16,
    },
    statButtonLast: {
        flex: 1,
        alignItems: 'center',
        paddingLeft: 16,
    },
    statValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    statLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.9)',
        marginTop: 2,
    },
    profilePictureSection: {
        marginTop: -64,
        paddingHorizontal: 16,
    },
    profilePictureContainer: {
        alignItems: 'center',
    },
    profilePictureWrapper: {
        width: 128,
        height: 128,
        borderRadius: 9999,
        backgroundColor: '#FFFFFF',
        padding: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    profilePictureWrapperDark: {
        width: 128,
        height: 128,
        borderRadius: 9999,
        backgroundColor: '#1F2937',
        padding: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    profilePicture: {
        width: '100%',
        height: '100%',
        borderRadius: 9999,
        overflow: 'hidden',
        backgroundColor: '#E5E7EB',
    },
    profilePictureDark: {
        width: '100%',
        height: '100%',
        borderRadius: 9999,
        overflow: 'hidden',
        backgroundColor: '#374151',
    },
    profileImage: {
        width: '100%',
        height: '100%',
    },
    profileImagePlaceholder: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#D1D5DB',
    },
    profileImagePlaceholderDark: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4B5563',
    },
    actionButtons: {
        flexDirection: 'row',
        width: '100%',
        marginTop: 16,
    },
    followButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
        backgroundColor: '#3B82F6',
    },
    followButtonFollowing: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 8,
        backgroundColor: '#DBEAFE',
        borderWidth: 1,
        borderColor: '#93C5FD',
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    followButtonText: {
        marginLeft: 8,
        fontWeight: '600',
    },
    messageButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#DBEAFE',
        borderWidth: 1,
        borderColor: '#93C5FD',
    },
    messageButtonText: {
        marginLeft: 8,
        fontWeight: '600',
        color: '#1E40AF',
    },
});

export default ProfileHeaderStyles;
